name: Deploy Workflows to Azure Logic App

on:
  push:
    branches: ["main"]

env:
  LOGIC_APP_NAME: 'logicappscicddemo'
  PACKAGE_NAME: '${{ github.workspace }}/package.zip'
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Create Workflow Archive
      uses: ihiroky/archive-action@v1
      with:
        root_dir: './LogicApps'
        file_path: ${{ env.PACKAGE_NAME }}         
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Run Azure Logic Apps Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.LOGIC_APP_NAME }}
        package: ${{ env.PACKAGE_NAME }}
